# Generated by Django 5.0.14 on 2026-06-06 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentplan',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
