# Generated by Django 5.0.14 on 2026-10-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_rename_create_at_investmentplan_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('usdt', 'USDT'), ('usdt2', 'USDT (ERC-20)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('roi', 'ROI Credit'), ('referral_bonus', 'Referral Bonus'), ('investment', 'Investment')], max_length=20),
        ),
    ]
