# Generated by Django 5.0.14 on 2026-10-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bank_account_name',
            new_name='usdt_erc20_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bank_name',
        ),
    ]
