# Generated by Django 5.0.14 on 2026-06-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='updated_up',
            new_name='updated_at',
        ),
    ]
