# Generated by Django 5.0.14 on 2026-06-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0002_rename_updated_up_withdrawal_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='bank_name',
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='method',
            field=models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('usdt', 'USDT')], max_length=20),
        ),
    ]
