# Generated by Django 5.0.14 on 2026-10-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0003_remove_withdrawal_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='method',
            field=models.CharField(choices=[('bitcoin', 'Bitcoin'), ('ethereum', 'Ethereum'), ('usdt', 'USDT (TRC-20)'), ('usdt2', 'USDT (ERC-20)')], max_length=20),
        ),
    ]
